Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -46,9 +46,9 @@ jobs:
       - run:
           name: Install Google Cloud SDK
           command: |
-            curl https://sdk.cloud.google.com | bash
-            exec -l $SHELL
-            gcloud init
+            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
+            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
+            sudo apt-get update && sudo apt-get install google-cloud-sdk
       - run:
           name: Authenticate with Google Cloud
           command: |
@@ -69,52 +69,6 @@ jobs:
       - store_artifacts:
           path: /home/circleci/project/test-script-/target/cucumber-report-html/cucumber-html-reports/feature-overview.html
 
-  check_application_url:
-    docker:
-      - image: circleci/openjdk:11-jdk
-    steps:
-      - checkout
-      - attach_workspace:
-          at: .
-      - run:
-          name: Install Google Cloud SDK
-          command: |
-            curl https://sdk.cloud.google.com | bash
-            exec -l $SHELL
-            gcloud init
-      - run:
-          name: Test Application URL
-          command: |
-            APPLICATION_URL=https://appadminqa.pippintitle.com
-            echo "Testing Application URL: $APPLICATION_URL"
-            RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" $APPLICATION_URL)
-            echo "Response code: $RESPONSE_CODE"
-            if [ $RESPONSE_CODE -eq 200 ]; then
-              echo "Application URL test succeeded. Response code: $RESPONSE_CODE"
-            else
-              echo "Application URL test failed. Response code: $RESPONSE_CODE"
-              exit 1
-            fi
-      - run:
-          name: Download CSS from Google Cloud Storage
-          command: |
-            BUCKET_NAME=your-gcp-bucket-name
-            FILE_PATH="automation-css/cucumber-report-html (6).zip"
-
-            # Ensure that gcloud and gsutil are in the PATH
-            export PATH=$PATH:/root/google-cloud-sdk/bin
-
-            gcloud auth activate-service-account --key-file=service-account.json
-
-            # Quote the FILE_PATH to handle special characters
-            gsutil cp "gs://$automation-css/$automation-css/cucumber-report-html (6).zip" .
-
-      - persist_to_workspace:
-          root: .
-          paths:
-            - application-url-test-results.txt
-            - cucumber-report-html (6).zip
-
   check_application:
     docker:
       - image: circleci/openjdk:11-jdk
@@ -129,9 +83,9 @@ jobs:
       - run:
           name: Install Google Cloud SDK
           command: |
-            curl https://sdk.cloud.google.com | bash
-            exec -l $SHELL
-            gcloud init
+            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
+            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
+            sudo apt-get update && sudo apt-get install google-cloud-sdk
       - run:
           name: Authenticate with Google Cloud
           command: |
@@ -140,6 +94,24 @@ jobs:
             gcloud auth activate-service-account --key-file=service-account.json
             gcloud auth list
             cat $BASH_ENV
+      - run:
+          name: Test Application URL
+          command: |
+            APPLICATION_URL=https://appadminqa.pippintitle.com
+            echo "Testing Application URL: $APPLICATION_URL"
+            RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" $APPLICATION_URL)
+            echo "Response code: $RESPONSE_CODE"
+            if [ $RESPONSE_CODE -eq 200 ]; then
+              echo "Application URL test succeeded. Response code: $RESPONSE_CODE"
+            else
+              echo "Application URL test failed. Response code: $RESPONSE_CODE"
+              exit 1
+            fi
+      - run:
+          name: Upload Test Results CSS to GCS
+          command: |
+            gsutil cp /home/circleci/project/test-script-/target/cucumber-report-html/cucumber-html-reports/style.css gs://your-gcs-bucket/path/to/destination/
+
       - run:
           name: Run Application Tests
           command: |
@@ -163,7 +135,7 @@ jobs:
           command: |
             ARTIFACT_LINK="https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_ID}/artifacts/0/artifacts/file-Features-AbstractorCreation-feature.html"
             echo "Artifact Link: $ARTIFACT_LINK"
-  
+
 workflows:
   version: 2
   build:
@@ -173,12 +145,9 @@ workflows:
       - build_and_check:
           requires:
             - "list-1password-vaults"
-      - check_application_url:
-          requires:
-            - build_and_check
       - check_application:
           requires:
-            - check_application_url
+            - build_and_check
       - notify-slack:
           requires:
             - check_application
